name: GetScreen Windows 10 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=tryemail1234567890@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://raw.githubusercontent.com/rudranshgoel1/windows2/main/down.bat" -OutFile "down.bat"
         cmd /c down.bat

      - name: Run Script
        run: python chrome.py
        
      - name: Time Counter
        run: cmd /c loop.bat
